[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Tốc độ in log ra màn hình Terminal (ESP32 thường dùng 115200 thay vì 9600)
monitor_speed = 115200

; Danh sách thư viện (Hoạt động giống hệt "dependencies" trong package.json)
lib_deps =
  ; 1. Bộ thư viện cho cảm biến nhiệt độ/độ ẩm DHT22
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14

  ; 2. Thư viện đọc data cho cảm biến bụi mịn PMS5003
  fu-hsi/PMS Library

  ; 3. Thư viện MQTT (Trạm phát sóng để gửi data lên HiveMQ)
  knolleary/PubSubClient @ ^2.8

  ; 4. Thư viện xử lý JSON (Cực kỳ quan trọng)
  bblanchon/ArduinoJson @ ^7.0.4